#!/usr/bin/env bash
# generated by sage generate — do not edit. canonical: scripts/sage_harness/hooks (단일소스).
ROOT="${SAGE_PROJECT_ROOT:-${CODEX_PROJECT_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}}"
export SAGE_HOOK_CORE_DIR="$ROOT/scripts/sage_harness/hooks"
[ -z "${SAGE_PROFILE:-}" ] && [ -f "$ROOT/sage/project-profile.json" ] && export SAGE_PROFILE="$ROOT/sage/project-profile.json"
exec bash "$ROOT/scripts/sage_harness/hooks/adapters/codex/post-tool-logger.sh" "$@"
