#!/bin/bash
# generated by sage generate - project hook adapter; do not edit.
PROJECT_ROOT="${SAGE_PROJECT_ROOT:-${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}}"
CORE_DIR="$PROJECT_ROOT/scripts/sage_harness/hooks"
[ -z "${SAGE_PROFILE:-}" ] && [ -f "$PROJECT_ROOT/sage/project-profile.json" ] && export SAGE_PROFILE="$PROJECT_ROOT/sage/project-profile.json"
PY="${SAGE_PYTHON:-python3}"; command -v "$PY" >/dev/null 2>&1 || PY=python
exec "$PY" "$CORE_DIR/runtime/run_hook.py" --runtime claude --hook chatforyou-dual-implementation-doc-gate --root "$PROJECT_ROOT" --core-dir "$CORE_DIR"
